-- Instagram Tokens Table
-- Note: This table already exists in the database with the structure below.
-- This file is for reference only.

-- Existing table structure:
-- CREATE TABLE instagram_tokens (
--   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
--   client_id UUID UNIQUE NOT NULL REFERENCES web_clients(id),
--   access_token TEXT NOT NULL,
--   instagram_user_id TEXT NOT NULL,
--   instagram_username TEXT NOT NULL,
--   token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--   updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
--
-- CREATE INDEX idx_instagram_tokens_client_id ON instagram_tokens(client_id);
-- CREATE INDEX idx_instagram_tokens_expires_at ON instagram_tokens(token_expires_at);
